version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - redis
      - kafka

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE=http://api:8080
    ports:
      - "5173:4173"
    depends_on:
      - api

  cassandra:
    image: cassandra:5.0
    container_name: ugr-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:7.4
    container_name: ugr-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: ugr-zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    container_name: ugr-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

volumes:
  cassandra_data:
